[package]
name = "assets-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
filesize = "0.2.0"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
zip = "2.1"


[dev-dependencies]
serial_test = "3"